services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    expose:
      - "3000:3000"

#   mediafusion:
#     image: mhdzumair/mediafusion:4.3.15
#     ports:
#       - "8000:8000"
#     env_file: .env
#     depends_on:
#       mongodb:
#         condition: service_healthy
#       redis:
#         condition: service_healthy
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#       interval: 1m
#       timeout: 10s
#       retries: 5
#       start_period: 10s
#     restart: unless-stopped

#   mongodb:
#     image: mongo:latest
#     volumes:
#       - mongo-data:/data/db
#     ports:
#       - "27017"
#     restart: unless-stopped
#     healthcheck:
#       test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
#       interval: 10s
#       timeout: 10s
#       retries: 5
#       start_period: 40s

#   redis:
#     image: redis:latest
#     ports:
#       - "6379"
#     volumes:
#       - redis-data:/data
#     command: redis-server --appendonly yes --save 60 1
#     restart: unless-stopped
#     healthcheck:
#       test: ["CMD", "redis-cli", "ping"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   mongo-data:
#     driver: local
#   redis-data:
#     driver: local