services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    expose:
      - 3000
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.aio.rule=Host(`YOUR_PUBLIC_HOSTNAME`)"
    #   - "traefik.http.routers.aio.entrypoints=websecure"
    #   - "traefik.http.routers.aio.tls.certresolver=myresolver"s